<?php

namespace AppBundle\Repository;

/**
 * gameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gameRepository extends \Doctrine\ORM\EntityRepository
{
}
